### PR TITLE
 :cop: better test than regret

### PR DESCRIPTION
**Pull request by sarbbottam**
raised on top of #28

### CODE REVIEW

**Comment by ta2edchimp** [comment]
LGTM. :+1:

#28 could be closed then?

**Comment by sarbbottam** [comment]
Will loose the commit history, Should we
* merge #28 
* rebase #29 
* merge #29

**Comment by ta2edchimp** [comment]
Ah, I see ... Sounds reasonable.
You want to »squash merge« then, I guess.

**Comment by sarbbottam** [comment]
yep

**Comment by ta2edchimp** [comment]
Let's do it!
I'm 😴 for now ...

**Pull request merged**
