### PR TITLE
chore: add myself as a contributor

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by ljharb** [comment]
@ta2edchimp i'm trying to make a release, but i'm not sure how i'm supposed to do it. is it documented anywhere?

**Comment by ta2edchimp** [comment]
Unfortunately, it's not (yet) documented. We removed the automatic release using `semantic-release`, but never updated the docs.

* I usually tag the version `npm version (major|minor|patch)`,
* build all the things `npm run build`
* and publish the release `npm publish`

**Comment by ljharb** [comment]
Sounds great, will do

**Comment by ljharb** [comment]
Done in #299 and #300.

**Pull request merged**
