### PR TITLE
fix(deps): update dependencies to their latest versions

### PR DESCRIPTION
**Pull request by sarbbottam**
refer https://github.com/kentcdodds/eslint-find-new-rules/pull/33 for further details

@ta2edchimp please review.

### CODE REVIEW

**Comment by ta2edchimp** [comment]
Hmm ... could you please enable the renamed version again in travis?

**Comment by ta2edchimp** [comment]
Other than that, I'd give it a go if ci checks succeed.

(Man, you're productive today :wink:)

**Comment by sarbbottam** [comment]
[build is enabled](https://travis-ci.org/sarbbottam/eslint-find-rules/jobs/122361391), but it failed, but the strange fact is why it did not complain here 😢

**Comment by sarbbottam** [comment]
Ok, I see the build status now!

>Man, you're productive today

😝

**Comment by ta2edchimp** [comment]
Hmm... seems to be related to `eslint@2.7.0`.

**Comment by ta2edchimp** [comment]
I'll enable `greenkeeper` for this repo once I arrive in the office. Then we'd automatically receive PRs for updated dependencies and would see if sth. breaks because of an updated dep ...

**Comment by ta2edchimp** [comment]
>I'll enable greenkeeper for this repo once I arrive in the office. Then we'd automatically receive PRs for updated dependencies and would see if sth. breaks because of an updated dep ...

Could you run `greenkeeper enable` for this repo, please? Admin access is required to run it (obviously).

**Comment by ta2edchimp** [comment]
Ok, I narrowed it down to be an issue with eslint plugins not being found on installations using `npm@2.x`. I found situations where either `eslint-plugin-import` (depency of `eslint-config-kentcdodds`) or `eslint-plugin-ava` could not be resolved.

Guess what? I'm so fed up with `npm@2.x` and the ways it makes nonsense (and steals time), I'd prefer to ditch it in the CI tests and revert back to using only the latest npm versions. If an older npm version ever causes trouble in a real situation, we can look into it **then**.

So for now, I'd propose you'd change the [`.travis.yml`](https://github.com/sarbbottam/eslint-find-rules/blob/master/.travis.yml#L11-L15) back to

```YAML
before_install:
  - npm i -g npm@^3.0.0
```

commit it into this PR, and it'll almost resolve itself. We could finally make a release and start working on the real things instead of messing around with the complementary build stuff that brakes because of an old npm version (that really makes me angry 😜 ).

**Comment by sarbbottam** [comment]
Will close this PR in favor of `greenkeeper`

**Comment by sarbbottam** [comment]
Closing in favor of #24

**Pull request closed without merging**
